// <auto-generated />
using System;
using ES.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ES.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220104025358_NLTT")]
    partial class NLTT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ES.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ES.Models.SoLieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("G_CSLN")
                        .HasColumnType("int");

                    b.Property<int>("G_HT")
                        .HasColumnType("int");

                    b.Property<int>("G_SLN")
                        .HasColumnType("int");

                    b.Property<int>("G_TK")
                        .HasColumnType("int");

                    b.Property<int>("MT_CSLN")
                        .HasColumnType("int");

                    b.Property<int>("MT_HT")
                        .HasColumnType("int");

                    b.Property<int>("MT_SLN")
                        .HasColumnType("int");

                    b.Property<int>("MT_TK")
                        .HasColumnType("int");

                    b.Property<int>("SK_CSLN")
                        .HasColumnType("int");

                    b.Property<int>("SK_HT")
                        .HasColumnType("int");

                    b.Property<int>("SK_SLN")
                        .HasColumnType("int");

                    b.Property<int>("SK_TK")
                        .HasColumnType("int");

                    b.Property<int>("T_CSLN")
                        .HasColumnType("int");

                    b.Property<int>("T_HT")
                        .HasColumnType("int");

                    b.Property<int>("T_SLN")
                        .HasColumnType("int");

                    b.Property<int>("T_TK")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SoLieu");
                });
#pragma warning restore 612, 618
        }
    }
}
